# -*- coding: utf-8 -*-
"""my_algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z06mrfGCzaM-i7hz1Z9TFCa92XeKBhpk
"""

def quick_sort(arr):
  """Функция быстрой сортировки"""
  # Логика алгоритма быстрой сортировки
  if len(arr) <= 1:
    return arr
  pivot = arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]
  return quick_sort(left) + middle + quick_sort(right)